# generated by datamodel-codegen:
#   filename:  AitelierControlPlane.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AitelierControlPlane(RootModel[Any]):
    root: Annotated[Any, Field(title='AitelierControlPlane')]


class ActiveRuns(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    active: Annotated[
        list[str],
        Field(description='Run IDs currently in-flight in this server process'),
    ]


class Command(BaseModel):
    cmd: str
    args: list[str] | None = None
    cwd: str | None = None
    env: dict[str, Any] | None = None


class Encoding(StrEnum):
    utf_8 = 'utf-8'
    base64 = 'base64'


class File(BaseModel):
    path: str
    content: str
    encoding: Encoding | None = None


class Sidecar(BaseModel):
    name: str
    cmd: str
    args: list[str] | None = None
    env: dict[str, Any] | None = None


class Prepare(BaseModel):
    install_agents: Annotated[
        list[str] | None,
        Field(description='Agent backends to JIT-install before the run.'),
    ] = None
    commands: list[Command] | None = None
    files: list[File] | None = None
    sidecars: Annotated[
        list[Sidecar] | None,
        Field(
            description='Long-lived processes started before the agent runs and torn down after.'
        ),
    ] = None


class Artifacts(BaseModel):
    fetch: Annotated[
        list[str] | None,
        Field(
            description='Paths to pull back after the agent finishes. Returned under `aitelier_artifacts` keyed by path.'
        ),
    ] = None


class Example(BaseModel):
    user: str
    assistant: str


class AitelierRequestExtension(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    workspace: Annotated[
        str | None,
        Field(
            description='Path inside the sandbox the agent should operate on. Maps to ACP `session/new.cwd`.'
        ),
    ] = None
    mcp_servers: Annotated[
        list[dict[str, Any]] | None,
        Field(
            description='MCP servers exposed to the agent. Maps to ACP `session/new.mcpServers`. Each entry is an MCP server descriptor (name, transport, url/command).',
            max_length=32,
        ),
    ] = None
    tool_allowlist: Annotated[
        list[str] | None,
        Field(
            description='Tools the agent is allowed to invoke. Claude-only: passed via `session/new` `_meta.claudeCode.options.allowedTools`. Rejected (400) on other backends, which have no ACP channel for it — use `approval_mode` for tool access there.',
            max_length=256,
        ),
    ] = None
    max_turns: Annotated[
        int | None,
        Field(
            description='Cap on agent reasoning turns. Claude-only: passed via `session/new` `_meta.claudeCode.options.maxTurns`. Rejected (400) on other backends; bound those runs with the top-level `timeout` instead.',
            ge=1,
        ),
    ] = None
    reasoning_effort: Annotated[
        str | None,
        Field(
            description="Inner-agent reasoning effort, mapped to the backend's advertised `thought_level` option (codex: low/medium/high/xhigh; claude: low/medium/high/xhigh/max). Validated against the backend's advertised values; an unknown value fails fast. Falls back to the top-level OpenAI `reasoning_effort` when unset."
        ),
    ] = None
    approval_mode: Annotated[
        str | None,
        Field(
            description="Inner-agent approval / sandboxing preset, mapped to the backend's advertised `mode` option (codex: read-only/auto/full-access; claude: auto/default/acceptEdits/plan/dontAsk/bypassPermissions). Validated against advertised values."
        ),
    ] = None
    prepare: Annotated[
        Prepare | None,
        Field(
            description='Pre-flight sandbox setup. Shape: {install_agents, commands, files, sidecars}. Each phase runs in order; a failure aborts before the agent starts.'
        ),
    ] = None
    artifacts: Annotated[
        Artifacts | None, Field(description='Post-flight file fetch from the sandbox.')
    ] = None
    trace_tag: Annotated[
        str | None,
        Field(
            description='Free-form tag stamped on the run row. Query via `/v1/runs?trace_tag=...`.'
        ),
    ] = None
    parent_run_id: Annotated[
        str | None,
        Field(
            description="Optional pointer to a parent run for multi-agent workflows. Pure pass-through: recorded on this child's row, queryable via `/v1/runs?parent_run_id=X`. Aitelier enforces no semantics (no FK, no cycle check, no cascade). Orchestrators above aitelier own the meaning."
        ),
    ] = None
    examples: Annotated[
        list[Example] | None,
        Field(
            description='Few-shot examples. Each `{user, assistant}` pair is folded into the system prompt under `## Examples`.',
            max_length=100,
        ),
    ] = None
    allow_tool_drop: Annotated[
        bool | None,
        Field(
            description="Escape hatch: when true, OpenAI `tools` / `tool_choice` are silently dropped on the agent path instead of 400ing. For consumers whose transport sends `tools` per global config and can't suppress per-profile (e.g. Hermes)."
        ),
    ] = False


class CancelAck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: str
    cancelled: Annotated[
        bool, Field(description='True when the cancellation signal was delivered')
    ]


class Method(StrEnum):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'


class Endpoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: Method
    path: str


class Capabilities(BaseModel):
    available: bool
    reason: Annotated[str | None, Field(description='Set when available is false')] = (
        None
    )


class Litellm(BaseModel):
    reachable: bool
    base_url: Annotated[
        str | None,
        Field(description='Omitted in hosted mode (when service.api_key is set)'),
    ] = None
    models: list[str] | None = None
    reason: str | None = None


class SandboxAgent(BaseModel):
    reachable: bool
    base_url: Annotated[
        str | None,
        Field(description='Omitted in hosted mode (when service.api_key is set)'),
    ] = None
    agents: list[str] | None = None
    reason: str | None = None


class Dependencies(BaseModel):
    litellm: Annotated[Litellm | None, Field(title='LitellmDep')] = None
    sandbox_agent: Annotated[SandboxAgent | None, Field(title='SandboxAgentDep')] = None


class Model(BaseModel):
    name: str
    response_format: Annotated[
        Any | None,
        Field(description='Per-model response_format capabilities, when known'),
    ] = None


class Discovery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    service: Literal['aitelier']
    version: Annotated[str, Field(description='Semantic version of the aitelier core')]
    api_version: Annotated[str, Field(description='Major API version (e.g. v1)')]
    timestamp: AwareDatetime
    endpoints: Annotated[
        list[Endpoint],
        Field(
            description='HTTP endpoint inventory, derived from the live FastAPI routes'
        ),
    ]
    capabilities: Annotated[
        dict[str, Capabilities],
        Field(
            description='Each capability is true iff its dependencies were reachable at probe time'
        ),
    ]
    dependencies: Annotated[Dependencies, Field(title='Dependencies')]
    models: Annotated[
        list[Model] | None,
        Field(
            description='Convenience list of models callable on /v1/chat/completions (LiteLLM aliases + curated agent: routes). The authoritative listing is GET /v1/models.'
        ),
    ] = None
    schemas: Annotated[
        dict[str, str], Field(description='Map of schema name → fetch URL')
    ]
    known_limitations: list[str]


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'


class Dependencies1(BaseModel):
    reachable: bool | None = None


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Annotated[
        Status,
        Field(
            description='`ok` unless the (opportunistically-read) discovery cache shows a tracked dependency unreachable, then `degraded`. Always `ok` on cold start — check `dependencies_probed`.'
        ),
    ]
    version: str
    timestamp: AwareDatetime
    dependencies_probed: Annotated[
        bool | None,
        Field(
            description="False until /v1/discovery has warmed the dependency cache. Lets a consumer tell 'deps checked and healthy' apart from 'deps never probed'."
        ),
    ] = None
    known_limitations: list[str] | None = None
    dependencies: Annotated[
        dict[str, Dependencies1] | None,
        Field(
            description='Per-dependency reachability summary from the discovery cache. Omitted on cold start (before /v1/discovery has run).'
        ),
    ] = None


class State(StrEnum):
    pending = 'pending'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'
    orphaned = 'orphaned'


class Kind(StrEnum):
    complete = 'complete'
    embed = 'embed'
    agent = 'agent'


class Status1(Enum):
    ok = 'ok'
    error = 'error'
    cancelled = 'cancelled'
    NoneType_None = None


class Run(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: Annotated[
        str,
        Field(
            description='128-bit id as 32 lowercase hex chars — a valid W3C/OpenTelemetry trace id, so the run is addressable by this id in any OTLP backend. (Pre-2026-06 runs carry a legacy timestamp-style id.)'
        ),
    ]
    trace_id: Annotated[
        str | None,
        Field(
            description="Equals run_id — one canonical id. Since run_id is now a W3C trace id, this is the trace's id in any OTLP backend; one trace per run."
        ),
    ] = None
    state: Annotated[
        State,
        Field(
            description="Lifecycle state. `orphaned` = the row was running when a prior aitelier process exited; Sandbox Agent has no resume API yet, so it's terminal."
        ),
    ]
    kind: Kind
    agent_id: Annotated[
        str | None,
        Field(description='Agent backend name (claude, codex, ...) when kind=agent.'),
    ] = None
    model: str | None = None
    started_at: AwareDatetime | None = None
    ended_at: AwareDatetime | None = None
    duration_ms: Annotated[
        int | None,
        Field(
            description='Wall-clock run duration in milliseconds (ended_at − started_at); null until the run ends. Maps to the OTel span duration.'
        ),
    ] = None
    trace_tag: str | None = None
    correlation_id: str | None = None
    parent_run_id: Annotated[
        str | None,
        Field(
            description='Optional pointer to a parent run for multi-agent workflows. Pure pass-through: aitelier records it and lets consumers query `/v1/runs?parent_run_id=X`, but enforces no semantics (no FK, no cycle check, no cascade). Orchestrators above aitelier own the meaning.'
        ),
    ] = None
    sandbox_backend: Annotated[
        str | None,
        Field(
            description='`local` if the SA URL is loopback, `remote` otherwise. Stamped at agent-call time.'
        ),
    ] = None
    sandbox_url: str | None = None
    sandbox_server_id: Annotated[
        str | None,
        Field(
            description='ACP server_id this run was bound to. Future SA session-resume APIs can adopt it.'
        ),
    ] = None
    workspace: str | None = None
    environment: Annotated[
        dict[str, Any] | None,
        Field(description='Snapshot of mcp_servers + tool_allowlist at run time.'),
    ] = {}
    input_tokens: Annotated[
        int | None,
        Field(
            description="Null when the backend reported no usage (some agent backends) or the run isn't finalized — distinct from a real 0."
        ),
    ] = None
    output_tokens: int | None = None
    total_tokens: int | None = None
    cached_read_tokens: Annotated[
        int | None,
        Field(
            description='Prompt-cache read tokens (e.g. claude). Null when the backend reports no cache info — distinct from a real 0. Cache-read dominates warm-run volume and is priced far below fresh input.'
        ),
    ] = None
    cached_write_tokens: Annotated[
        int | None,
        Field(
            description='Prompt-cache write/creation tokens. Null when the backend reports no cache info.'
        ),
    ] = None
    cost_usd: float | None = None
    finish_reason: str | None = None
    tool_call_count: int | None = None
    status: Status1 | None = None
    error_type: str | None = None
    error_msg: str | None = None
    system_prompt_hash: Annotated[
        str | None,
        Field(
            description='SHA-256 of the system prompt actually sent to the provider; lets dashboards group runs by prompt variant.'
        ),
    ] = None
    result: Annotated[
        dict[str, Any] | None,
        Field(
            description="Final result payload from the run. For LLM/embed kinds: the OpenAI-shape response body. For agent kinds: the aggregated done event (content, finish_reason, usage, tool_calls). Empty object if the run hasn't reached a terminal state."
        ),
    ] = {}
    metadata: dict[str, Any] | None = {}
    request_body: Annotated[
        dict[str, Any] | None,
        Field(
            description="Caller's request body as received (pre-fold, pre-translate). For ChatCompletionRequest / AsyncRunRequest / EmbeddingsRequest. Null for historical runs from before the v4 storage migration. Projection-redacted at the HTTP boundary."
        ),
    ] = None
    rendered_messages: Annotated[
        list[dict[str, Any]] | None,
        Field(
            description="Message list after aitelier's agent-path translations (system-prompt fold, response_format injection) — what actually went on the wire. Null when no translation applies (embed runs, pre-v4 runs)."
        ),
    ] = None
    manifest: Annotated[
        dict[str, Any] | None,
        Field(
            description='On-disk run manifest (runs/{id}/manifest.json), merged in by GET /v1/runs/{id} when present.'
        ),
    ] = None
    prompt: Annotated[
        str | None,
        Field(
            description='On-disk rendered prompt (runs/{id}/prompt.txt), merged in by GET /v1/runs/{id} when present.'
        ),
    ] = None


class RunEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: Annotated[
        int | None,
        Field(
            description='Monotonically-increasing per-process insert order. Not stable across stores.'
        ),
    ] = None
    run_id: str
    seq: Annotated[
        int,
        Field(
            description='Per-run monotonic sequence. Use with ?since_seq= to paginate without re-fetching.'
        ),
    ]
    kind: Annotated[
        str,
        Field(
            description='Event family. Common: start, delta, thought, tool_call, tool_result, finish, error, cancelled, plus agent-path observability — context_usage, plan, mode, available_commands, permission_request, tool_denied. Open-ended; new kinds may appear without a schema bump.'
        ),
    ]
    ts: AwareDatetime | None = None
    payload: Annotated[
        dict[str, Any] | None,
        Field(
            description="Event-specific fields. delta/thought: {content}. tool_call: {server, tool, input, locations, tool_kind}. tool_result: {tool, output, elapsed_ms}. start: {agent, sandbox, workspace} (sandbox is the symbolic 'local'|'remote', not an internal URL). context_usage: {size, used}. permission_request: {tool}. tool_denied: {tool, reason}. cancelled: {content, tool_calls} — partial work captured at cancel time."
        ),
    ] = None


class RunScore(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        int | None,
        Field(
            description='Server-assigned row id. Populated on response; absent on request.'
        ),
    ] = None
    run_id: Annotated[
        str,
        Field(
            description='The run this score is against. Must reference an existing row in `runs`.'
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="Score name (e.g. 'helpfulness', 'factuality'). Charset-restricted because it flows into log lines and aggregate group-by queries.",
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9_\\-\\.]+$',
        ),
    ]
    value: Annotated[
        float,
        Field(
            description='Score value. Unconstrained range because rubrics differ (0..1 normalized, 1..5 Likert, raw token counts, latency budgets, etc.). Consumers normalize as they need.'
        ),
    ]
    evaluator: Annotated[
        str,
        Field(
            description="Who or what produced the score (e.g. 'gpt-4o-judge', 'human:reviewer-3', 'rubric/v2'). Charset-restricted for the same reasons as `name`, but allows ':' and '/' for namespacing.",
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9_\\-\\.:/]+$',
        ),
    ]
    comment: Annotated[
        str | None,
        Field(
            description='Free-form grader rationale. Defaults to null.', max_length=4096
        ),
    ] = None
    metadata: Annotated[
        dict[str, Any] | None,
        Field(
            description='Opaque grader-supplied metadata (rubric version, model temperature, dataset slice, etc.).'
        ),
    ] = None
    created_at: Annotated[
        AwareDatetime | None,
        Field(description='Server-assigned creation timestamp. Populated on response.'),
    ] = None


class Schedule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    task: Annotated[
        dict[str, Any],
        Field(
            description="Task dict to dispatch when the schedule fires. Shape mirrors a primitive's request body plus {kind: 'complete'|'embed'|'agent', name: str}."
        ),
    ]
    interval_seconds: Annotated[
        int | None,
        Field(description='Recurring fire interval. Mutually exclusive with at_iso.'),
    ] = None
    at_iso: Annotated[
        AwareDatetime | None,
        Field(
            description='One-shot trigger time. Mutually exclusive with interval_seconds.'
        ),
    ] = None
    webhook_url: Annotated[
        str | None,
        Field(
            description='Optional callback URL. Each fire enqueues a durable POST with {schedule_id, run_id, result}.'
        ),
    ] = None
    next_run_at: AwareDatetime | None = None
    last_run_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class TraceRecord(BaseModel):
    trace_id: str
    started_at: str
    ended_at: str | None = None
    duration_ms: Annotated[
        int | None, Field(description='Wall-clock duration in ms; null until ended.')
    ] = None
    model: str | None = None
    kind: str | None = None
    finish_reason: str | None = None
    tool_call_count: int | None = 0
    input_tokens: int | None = None
    output_tokens: int | None = None
    total_tokens: int | None = None
    cost_usd: float | None = None
    system_prompt_hash: str | None = None
    trace_tag: str | None = None
    parent_run_id: str | None = None
    status: str | None = None
    error_type: str | None = None
    error_msg: str | None = None
    metadata: dict[str, Any] | None = {}


class GroupBy(StrEnum):
    trace_tag = 'trace_tag'
    kind = 'kind'
    model = 'model'
    agent_id = 'agent_id'
    status = 'status'
    error_type = 'error_type'
    day = 'day'


class Bucket(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Annotated[
        str,
        Field(
            description='The group value (e.g. trace_tag name, model id, or YYYY-MM-DD day).'
        ),
    ]
    count: int
    total_tokens: int
    cost_usd: float
    error_count: int


class Totals(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    count: int
    total_tokens: int
    cost_usd: float
    error_count: int


class TracesAggregate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group_by: GroupBy
    groups: list[Bucket]
    total: Totals
